part of health;

/// List of all [HealthDataPoint] units.
enum HealthDataUnit {
  BEATS_PER_MINUTE,
  CALORIES,
  COUNT,
  DEGREE_FAHRENHEIT,
  GRAMS,
  INCHES,
  POUNDS,
  METERS,
  MILLIGRAM_PER_DECILITER,
  MILLIMETER_OF_MERCURY,
  MILLISECONDS,
  MINUTES,
  NO_UNIT,
  PERCENTAGE,
  SIEMENS,
  UNKNOWN_UNIT,
  LITER,
}
